# Generated by Django 5.2.17 on 2026-08-15 09:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiPredictionEvent',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requesting_role', models.CharField(editable=False, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('model_version', models.CharField(db_index=True, editable=False, max_length=120)),
                ('preprocessing_version', models.CharField(editable=False, max_length=120)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('validation_failed', 'Validation failed'), ('inference_failed', 'Inference failed'), ('model_unavailable', 'Model unavailable')], db_index=True, editable=False, max_length=32)),
                ('prediction_label', models.CharField(blank=True, editable=False, max_length=32)),
                ('model_probability', models.FloatField(blank=True, editable=False, null=True)),
                ('explanation', models.JSONField(blank=True, default=dict, editable=False)),
                ('requesting_user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='ai_prediction_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['requesting_user', '-created_at'], name='ai_audit_ai_request_2eea07_idx'), models.Index(fields=['status', '-created_at'], name='ai_audit_ai_status_307ec8_idx'), models.Index(fields=['model_version', '-created_at'], name='ai_audit_ai_model_v_d79f22_idx')],
            },
        ),
    ]
