# Generated by Django 5.2.17 on 2026-08-14 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('lab_test', 'Lab Test'), ('consultation', 'Consultation'), ('imaging', 'Imaging'), ('prescription', 'Prescription'), ('other', 'Other')], max_length=20)),
                ('occurred_on', models.DateField()),
                ('diagnosis', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='medical_records/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='appointments.appointment')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='accounts.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_records', to='accounts.patientprofile')),
            ],
            options={
                'ordering': ['-occurred_on', '-created_at'],
                'indexes': [models.Index(fields=['patient', '-occurred_on'], name='medical_rec_patient_a01946_idx'), models.Index(fields=['record_type', '-occurred_on'], name='medical_rec_record__97662d_idx')],
            },
        ),
    ]
