# Generated by Django 5.2.17 on 2026-08-14 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=16)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='accounts.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='accounts.patientprofile')),
            ],
            options={
                'ordering': ['scheduled_date', 'scheduled_time'],
                'indexes': [models.Index(fields=['patient', 'scheduled_date'], name='appointment_patient_f4324c_idx'), models.Index(fields=['doctor', 'scheduled_date'], name='appointment_doctor__4efb5b_idx'), models.Index(fields=['status', 'scheduled_date'], name='appointment_status_93b56b_idx')],
                'constraints': [models.UniqueConstraint(fields=('doctor', 'scheduled_date', 'scheduled_time'), name='unique_doctor_appointment_slot')],
            },
        ),
    ]
