# Generated by Django 5.2.17 on 2026-08-14 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('appointments', '0001_initial'),
        ('medical_records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('blood_test', 'Blood Test'), ('imaging', 'Imaging'), ('ecg', 'ECG'), ('urine_test', 'Urine Test'), ('other', 'Other')], max_length=20)),
                ('laboratory_name', models.CharField(blank=True, max_length=255)),
                ('report_date', models.DateField()),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('abnormal', 'Abnormal'), ('pending', 'Pending')], default='pending', max_length=16)),
                ('summary', models.TextField(blank=True)),
                ('interpretation', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='medical_reports/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_reports', to='appointments.appointment')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_reports', to='accounts.doctorprofile')),
                ('medical_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='medical_records.medicalrecord')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_reports', to='accounts.patientprofile')),
            ],
            options={
                'ordering': ['-report_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('is_normal', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='reports.medicalreport')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='medicalreport',
            index=models.Index(fields=['patient', '-report_date'], name='reports_med_patient_7ac78a_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalreport',
            index=models.Index(fields=['report_type', '-report_date'], name='reports_med_report__83890c_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalreport',
            index=models.Index(fields=['status', '-report_date'], name='reports_med_status_b3028f_idx'),
        ),
    ]
