# Generated by Django 5.2.17 on 2026-08-15 09:22

import apps.clinical_api.file_security
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='attachment_content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='attachment_original_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='attachment_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=apps.clinical_api.file_security.protected_upload_to),
        ),
    ]
